### ISSUE TITLE
“Sloth.app” can’t be opened because Apple cannot check it for malicious software.

### ISSUE THREAD

**Issue by nd7** [sveinbjornt/Sloth#24]
Trying to open the app following warning is shown. 
<img width="259" alt="image" src="https://user-images.githubusercontent.com/3672622/219814216-094e609c-bfa8-416f-a9ca-8f72a2fe87ce.png">

[I know the workaround - right click, open](https://support.apple.com/en-ca/guide/mac-help/mchleab3a043/mac)

It will be good to notarize and update the app so that this warning does not come up and user experience becomes better

**Comment by mehas** [comment]
I'm able to replicate in OSX v13.2.1

**Comment by rdanilin** [comment]
Same. I have Monterey 12.6.2 (21G320).

**Comment by sveinbjornt** [comment]
This is expected behaviour since the app is not notarized.

**Comment by riclf** [comment]
Same, no-go.
<img width="260" alt="Screenshot 2023-02-20 at 2 29 58 PM" src="https://user-images.githubusercontent.com/151512/220211459-cf845e8d-2b79-48aa-988b-778ebb95303d.png">

**Comment by riclf** [comment]
> This is expected behaviour since the app is not notarized.

So, its kind of useless then, right?  Not that its a useless app, but that it can't be used.

**Comment by arielallon** [comment]
Unfortunately, I cannot use the known workaround due to policies enforced on my work laptop.
Notarizing if possible would make the difference for me.

**Comment by rdanilin** [comment]
@sveinbjornt Do you have a workaround or now how not fix that?

**Comment by iAmWillShepherd** [comment]
Open _Security and Privacy_ in system preferences after trying to open. You should see a button beneath the _Allow apps downloaded from_ section of the pane. 

<img width="780" alt="Screen Shot 2023-02-22 at 2 43 40 PM" src="https://user-images.githubusercontent.com/1715082/220754440-ac47c40f-87c6-46ab-bb12-d66aaf0d16b4.png">

**Comment by riclf** [comment]
That's certainly how it was. On Ventura today, it looks different, as in my graphic, and unfortunately the "App Store and identified developers" selection is not the trick to do it. But in the Applications folder, if you right-click on sloth.app it gives the option to open it.

<img width="503" alt="Screenshot 2023-02-22 at 2 36 57 PM" src="https://user-images.githubusercontent.com/151512/220777023-a9223706-f836-4c5f-88c5-d215ceaab49c.png">

**Comment by mehas** [comment]
I have "App Store and identified developers" selected

> if you right-click on sloth.app it gives the option to open it

Sadly, this still gives me the same warning, I am unable to open the app. Same problem with the "Open Anyway" button:

<img width="454" alt="Screenshot 2023-02-23 at 10 19 54 AM" src="https://user-images.githubusercontent.com/389970/220950079-e6700550-eca1-40a9-8d19-304b44d6852c.png">

Result:

![Screenshot 2023-02-23 at 10 13 20 AM copy](https://user-images.githubusercontent.com/389970/220949057-ddf54450-6650-4dab-a163-103965b20f26.jpg)

_running OSX Ventura 13.2.1 (22D68)_

**Comment by sveinbjornt** [comment]
@mehas Sloth is decidedly *not* from an unidentified developer. I reluctantly pay Apple their obnoxious $100 tax every year just to be able to sign my free software.

<img width="692" alt="Screen Shot 2023-02-24 at 18 09 01" src="https://user-images.githubusercontent.com/654045/221256804-95593b76-82a6-4b28-aa5a-55548cefb475.png">

**Comment by riclf** [comment]
I hear you!  I make the same payment. Irks me but it is the toll required to play in their code yard. Grrrr.

-Ric

Richard Fink
Belvedere CA 94920
M:  415.302.7317 (World)
H:   415.435.1227 (Marin)
H:   415.409.6396 (SF)


From: Sveinbjorn Thordarson ***@***.***>
Reply-To: sveinbjornt/Sloth ***@***.***>
Date: Friday, February 24, 2023 at 10:10 AM
To: sveinbjornt/Sloth ***@***.***>
Cc: Richard Fink ***@***.***>, Comment ***@***.***>
Subject: Re: [sveinbjornt/Sloth] “Sloth.app” can’t be opened because Apple cannot check it for malicious software. (Issue #24)


@mehas<https://github.com/mehas> Sloth is decidedly not from an unidentified developer. I reluctantly pay Apple their obnoxious $100 tax every year just to be able to sign my free software.

[Screen Shot 2023-02-24 at 18 09 01]<https://user-images.githubusercontent.com/654045/221256804-95593b76-82a6-4b28-aa5a-55548cefb475.png>

**Comment by mehas** [comment]
Thanks for the update @sveinbjornt I didn't mean to imply otherwise. Just hoping to help by spring how too reproduce the bug. (I've heard similar frustrations from other iOS devs.)

**Comment by AndresReyesDev** [comment]
To fix it you just need to write this command in to the Terminal:

`xattr -r -d com.apple.quarantine /Applications/Sloth.app/`

And voilà!

**Comment by sveinbjornt** [comment]
@PicoMitchell Thank you for the feedback, sample code and links. I may look into this notarization business at some point in the future.

That being said, I have *very* limited time to work on these old macOS software projects of mine, time that is probably better spent improving them and fixing bugs rather than getting a headache working around Apple's disgusting and unconscionable gatekeeping, which is perpetually changing and getting more suffocating with every OS release. I'm already fuming over paying them 100 USD a year for the privilege of maintaining free, open source software.

Ctrl-click Open on the app isn't exactly rocket science, and most of my software is aimed at power-users who know this. The bad initial user experience is entirely on Apple and their attempt to slowly and surely push everything into the Mac App Store ... which I do not use and never will.
